services:
    kernel.listener.your_listener_name:
        class: HomeIndexBundle\EventListener\HomeExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }