<?php

namespace Home\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository
{
	// 每页显示的条数
	private $pagesize = 3;

	/**
	 * 获取指定页的分享内容列表
	 * @param  integer $page 当前页数
	 * @return array         数据结果集
	 */
	public function getSharelistByPage($page)
	{
		return "ShareRepository";
	}
}
